# Use the official Python image to run Python.
FROM python:3.10

# Declare environment variables as build arguments
# Kafka settings
ARG KAFKA_HOST
ARG KAFKA_PORT
ARG KAFKA_CONSUMER_USERNAME
ARG KAFKA_CONSUMER_PASSWORD
ARG KAFKA_CONSUMER_GROUP
ARG KAFKA_SOURCE_TOPIC
ARG KAFKA_DESTINATION_TOPIC

# Redis settings
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD

# PostgreSQL settings
ARG PG_WAREHOUSE_HOST
ARG PG_WAREHOUSE_PORT
ARG PG_WAREHOUSE_DBNAME
ARG PG_WAREHOUSE_USER
ARG PG_WAREHOUSE_PASSWORD

# Update components inside the container.
RUN apt-get update -y

# Copy all files into the container.
COPY . .

# Install the Python dependencies.
RUN pip install -r requirements.txt

# Install the certificate required to connect to resources in Yandex Cloud.
RUN mkdir -p /crt
RUN wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" --output-document /crt/YandexInternalRootCA.crt
RUN chmod 0600 /crt/YandexInternalRootCA.crt

# Switch to the src directory
WORKDIR /src

# Declare that we will run Python as the entrypoint.
ENTRYPOINT ["python"]

# Specifically, run the file app.py in the src directory.
CMD ["app.py"]
